### ISSUE TITLE
Use the basename to obtain files from the correct local night

### ISSUE THREAD

**Issue by danlegend5** [nespinoza/lcogtDD#1]
Dear Nestor,

Thankyou for providing this script for LCOGT data downloads. It has been very useful to me for understanding the interface to the LCOGT archive in python.

I am programming up my own version specific to a project I am working on.

I noticed that the best way to pull the data for a specific date YYYYMMDD is to query the archive on "basename=YYYYMMDD". This is because each file name contains the local date at the start of the night. So this simple modification guarantees you get all files from YYYYMMDD only from all sites. It would cut out a large amount of code that you have in the script for calculating dates. It could even be extended to ranges of dates.

All the best
Dan Bramich

**Comment by nespinoza** [comment]
Hi Dan,

 Thanks a lot for your input! I think this makes total sense. Will test it works on the following weeks and then add it to the code.

 I'll close this issue then ;-).

 Best,

Néstor

**Comment by danlegend5** [comment]
Dear Nestor,


Glad to know I could of assistance!

Dan


________________________________
