### ISSUE TITLE
End date ignored

### ISSUE THREAD

**Issue by igorandreoni** [nespinoza/lcogtDD#4]
Hi Nestor, I see that the block starting on line 193 kills the end date passed as argument by the user. 
https://github.com/nespinoza/lcogtDD/blob/45ed628e31f14851923bbcee425ce232959cae31/download_data.py#L193

The correct end date will be printed on the terminal, but the search will be only within 1 day from the start date. Please try it out and check if you see this problem, too. Thanks.

**Comment by igorandreoni** [comment]
Nevermind, I think I understand what it does with the dates. Apologies for the spam and thank you for making this awesome code public!

**Comment by nespinoza** [comment]
Glad to see it was not an issue after all! Thanks for checking @igorandreoni!
